# Generated by Django 4.2.2 on 2023-06-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=25)),
                ('credential', models.CharField(choices=[('Associate', 'Associate'), ("Bachelor's", "Bachelor'S"), ("Master's", "Master'S"), ('PhD', 'Phd')], max_length=10)),
                ('major', models.CharField(max_length=15)),
                ('gpa', models.DecimalField(decimal_places=3, max_digits=4)),
                ('coursework', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('proficiency', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Master', 'Master')], max_length=15)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
